apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtvo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtvo
  template:
    metadata:
      labels:
        app: rtvo
    spec:
      containers:
      - image: okteto.dev/rtvo:latest
        name: rtvo
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "33f165ff-c649-40fb-a186-11cf6e63bdc9"
        - name: Vless_Path
          value: "/vlordg"
        - name: Vmess_UUID
          value: "33f165ff-c649-40fb-a186-11cf6e63bdc9"
        - name: Vmess_Path
          value: "/vmdrdg"
        - name: Share_Path
          value: "/share233"
