apiVersion: apps/v1
kind: Deployment
metadata:
  name: pqg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pqg
  template:
    metadata:
      labels:
        app: pqg
    spec:
      containers:
      - image: okteto.dev/pqg:latest
        name: pqg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "music.163.com"
        - name: Vless_UUID
          value: "43d6dce9-cb7e-4a7a-95a8-50cc046cf005"
        - name: Vless_Path
          value: "/44lvdow"
        - name: Vmess_UUID
          value: "43d6dce9-cb7e-4a7a-95a8-50cc046cf005"
        - name: Vmess_Path
          value: "/33vmdow"
        - name: Share_Path
          value: "/share233"
