apiVersion: apps/v1
kind: Deployment
metadata:
  name: pqg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pqg
  template:
    metadata:
      labels:
        app: pqg
    spec:
      containers:
      - image: okteto.dev/pqg:latest
        name: pqg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "music.163.com"
        - name: Vless_UUID
          value: "11e2bd43-794a-4f52-928b-c3f9441c94fc"
        - name: Vless_Path
          value: "/446s"
        - name: Vmess_UUID
          value: "11e2bd43-794a-4f52-928b-c3f9441c94fc"
        - name: Vmess_Path
          value: "/445s"
        - name: Share_Path
          value: "/share233"
