apiVersion: apps/v1
kind: Deployment
metadata:
  name: cxk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cxk
  template:
    metadata:
      labels:
        app: cxk
    spec:
      containers:
      - image: okteto.dev/cxk:latest
        name: cxk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "www.ietf.org"
        - name: Vless_UUID
          value: "d068fa14-4bfe-4abb-9351-7149a4315211"
        - name: Vless_Path
          value: "/vlyna"
        - name: Vmess_UUID
          value: "d068fa14-4bfe-4abb-9351-7149a4315211"
        - name: Vmess_Path
          value: "/vmyna"
        - name: Share_Path
          value: "/share233"
