apiVersion: apps/v1
kind: Deployment
metadata:
  name: chti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chti
  template:
    metadata:
      labels:
        app: chti
    spec:
      containers:
      - image: okteto.dev/chti:latest
        name: chti
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "06b9d2f3-c549-4f9a-906d-becd2fe48014"
        - name: Vless_Path
          value: "/5ell"
        - name: Vmess_UUID
          value: "06b9d2f3-c549-4f9a-906d-becd2fe48014"
        - name: Vmess_Path
          value: "/5emm"
        - name: Share_Path
          value: "/share233"
