apiVersion: apps/v1
kind: Deployment
metadata:
  name: luia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luia
  template:
    metadata:
      labels:
        app: luia
    spec:
      containers:
      - image: okteto.dev/luia:latest
        name: luia
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "music.163.com"
        - name: Vless_UUID
          value: "176b1a8a-cbf7-4e2f-905c-1283915fe43f"
        - name: Vless_Path
          value: "/7kvlis"
        - name: Vmess_UUID
          value: "176b1a8a-cbf7-4e2f-905c-1283915fe43f"
        - name: Vmess_Path
          value: "/7kvmis"
        - name: Share_Path
          value: "/share233"
