apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckim
  template:
    metadata:
      labels:
        app: ckim
    spec:
      containers:
      - image: okteto.dev/ckim:latest
        name: ckim
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "music.163.com"
        - name: Vless_UUID
          value: "7f5fcdf2-a58d-4056-8395-2391f7b8ddc8"
        - name: Vless_Path
          value: "/h33lt"
        - name: Vmess_UUID
          value: "7f5fcdf2-a58d-4056-8395-2391f7b8ddc8"
        - name: Vmess_Path
          value: "/h44mt"
        - name: Share_Path
          value: "/share233"
