apiVersion: v1
kind: Service
metadata:
  name: chti
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: ""chti
    port: 8080
  selector:
    app: chti
